config/routes.rb
Kigendan::Application.routes.draw do

  root :to => 'pages#home'

  devise_for :users, :path => 'auth'

  resources :tracks, :only => [:index, :new, :create, :update, :destroy], :constraints => { :id => /[0-9]+/ } do
    get 'page:page', :action => :index, :on => :collection
  end

  resources :playlists, :only => [:index, :new, :create, :show, :update, :destroy], :constraints => { :id => /[0-9]+/ } do
    get 'page:page', :action => :index, :on => :collection
  end

  resources :users, :only => [:index, :update] do
    get 'page:page', :action => :index, :on => :collection
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  attr_accessible :track_id, :playlist_id, :position
  belongs_to :playlist
  belongs_to :track

  before_create :assign_position

  def assign_position
    if self.position.nil?
      self.position = self.playlist.max_position + 1;
    end
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  attr_accessible :description, :title, :listings_attributes, :now_playing
  has_many :listings, :dependent => :destroy
  has_many :tracks, :through => :listings, :order => 'listings.position'
  accepts_nested_attributes_for :listings, :allow_destroy => true

  before_save :play_if_needed

  alias_method :original_as_json, :as_json

  def as_json(options)
    json = original_as_json(options.merge(:only => [:id, :title, :description, :now_playing]))
    tracks = []
    listings.each do |l|
      track = l.track.as_json(:only => [:id, :title, :artist, :album, :genre])
      tracks << track.merge({ :listing_id => l.id, :position => l.position }) unless track.nil?
    end
    json.merge(:tracks => tracks)
  end

  def play_if_needed
    if self.now_playing
      Playlist.update_all(:now_playing => false)

      File.open(Rails.root.join('playlist.m3u'), 'w') do |file|
        tracks.each do |track|
          file.puts track.upload.path
        end
      end

      TelnetAdapter.send_command('files.reload')
    end
  end

  def max_position
    self.listings.blank? ? 0 : self.listings.last.position
  end

end

app/models/track.rb
class Track < ActiveRecord::Base

  attr_accessible :album, :artist, :bitrate, :duration, :genre, :release_date, :title, :upload, :upload_token
  has_many :listings, :dependent => :destroy
  has_many :playlists, :through => :listings
  
  mount_uploader :upload, TrackUploader

  alias_method :original_as_json, :as_json

  def as_json(options)
    json = original_as_json(options.merge(:only => [:id, :title, :artist, :album, :genre, :bitrate, :release_date]))
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # devise setup
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me

  attr_accessible :can_do_anything, :can_manage_tracks, :can_manage_users

  [:can_do_anything, :can_manage_tracks, :can_manage_users].each do |ability|
    define_method("#{ability}?") do 
      self.send(ability.to_sym) || self.can_do_anything
    end
  end

  alias_method :original_as_json, :as_json

  def as_json(options)
    json = original_as_json(options.merge(:only => [:id, :email, :can_do_anything, :can_manage_tracks, :can_manage_users, :can_manage_live_show, :can_broadcast]))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  before_filter :authenticate_user!

  before_filter do
    head :forbidden unless current_user.can_manage_tracks?
  end

  def index
    @playlists = Kaminari.paginate_array(Playlist.all(:order => "id")).page params[:page]        
    respond_to do |format|
      format.html 
      format.json { render :json => @playlists }
    end
  end

  def new
    @playlist = Playlist.new
    respond_to do |format|
      format.html 
      format.json { render :json => @playlist }
    end 
  end

  def create
    @playlist = Playlist.new(params[:playlist])
    @playlist.save
    respond_to do |format|
      format.html { redirect_to @playlist }
      format.json { render :json => @playlist }
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render :json => @playlist }
    end
  end

  def update
    @playlist = Playlist.find(params[:id])
    @playlist.update_attributes(params[:playlist])
    respond_to do |format|
      format.json { render :json => @playlist }
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

end
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter :authenticate_user!, :except => [:home]
  before_filter :allow_broadcaster, :except => [:home, :live]
  before_filter :allow_guest, :only => [:live]

  def home
    @playlist = Playlist.where(:now_playing => true).first
  end

  def live
  end

  def on_publish_done
    render :text => ''
  end

  def enable_live
    begin
      TelnetAdapter.send_command('live.enable')
    rescue
      render :text => '', :status => :internal_server_error
    else
      render :text => ''
    end
  end

  def disable_live
    begin
      TelnetAdapter.send_command('live.disable')
    rescue
      render :text => '', :status => :internal_server_error
    else
      render :text => ''
    end
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  
  before_filter :authenticate_user!
  
  before_filter do
    head :forbidden unless current_user.can_manage_tracks?
  end
  
  def index
    if params[:query] and ['title', 'artist', 'album', 'genre'].include? params[:field]
      @tracks = Track.where("#{params[:field]} ILIKE ?", "%#{params[:query]}%")
    else
      @tracks = Kaminari.paginate_array(Track.all(:order => "id")).page params[:page]
    end
    respond_to do |format|
      format.html
      format.json { render :json => @tracks }
    end
  end

  def new
    @track = Track.new
    respond_to do |format|
      format.html 
      format.json { render :json => @track }
    end
  end

  def create
    @track = Track.new(params[:track])
    respond_to do |format|
      if @track.save
        format.json { render :json => @track }
      else
        format.json { render :json => { :error => @track.errors[:upload] }, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @track = Track.find(params[:id])
    @track.update_attributes(params[:track])
    respond_to do |format|
      format.json { render :json => @track }
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  before_filter do 
    head :forbidden unless current_user.can_manage_users?
  end

  def index
    @users = Kaminari.paginate_array(User.all(:order => "id")).page params[:page]        
    respond_to do |format|
      format.html 
      format.json { render :json => @users }
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      render :json => @user
    else
      render :json => { :error => true }, :status => 403
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, controller, action, class_name = '')
    is_current = current_page?(url_for(:controller => '/' + controller, :action => action))
    content_tag(:li, :class => is_current ? 'active' : '') do
      link_to link_text, :controller => '/' + controller, :action => action, :page => nil
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %ul.nav
        = nav_link 'Home', 'pages', 'home'
        - if user_signed_in?
          - if current_user.can_manage_tracks?
            = nav_link 'Tracks', 'tracks', 'index'
            = nav_link 'Upload tracks', 'tracks', 'new'
            = nav_link 'Playlists', 'playlists', 'index'
            = nav_link 'New playlist', 'playlists', 'new'
          - if current_user.can_manage_users?
            = nav_link 'Users', 'users', 'index'
      %ul.nav.pull-right
        - if user_signed_in?
          = nav_link 'Edit profile', 'devise/registrations', 'edit'
          %li.nav-item
            = link_to 'Log out', destroy_user_session_path, :method => :delete
        - else
          = nav_link 'Log in', 'devise/sessions', 'new'
          = nav_link 'Sign up', 'devise/registrations', 'new'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{yield :title}
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/nav'
    .container
      - if notice
        .alert.alert-success 
          %button{ :type => 'button', :class => 'close', :'data-dismiss' => 'alert'} &times;
          = notice
      - if alert
        .alert.alert-error
          %button{ :type => 'button', :class => 'close', :'data-dismiss' => 'alert'} &times;
          = alert
      = yield

app/views/pages/home.html.haml
- provide :title, 'Home'
.status
  %h3
    - if @playlist.nil?
      Not playing
    - else
      Current playlist: #{@playlist.title}
%audio{:controls => 'controls'}
  %source{:src => 'http://localhost:8000/outer.mp3'}

app/views/playlists/_form.html.haml
= form_tag tracks_path, :method => :get, :class => 'tracks-search-form form-inline' do
  = text_field_tag :query, '', :placeholder => 'Query', :autocomplete => 'off'
  = submit_tag 'Search by', :class => 'btn'
  = select_tag :field, "<option value='title'>By title</option><option value='artist'>By artist</option><option value='album'>By album</option><option value='genre'>By genre</option>".html_safe

app/views/playlists/index.html.haml
- provide :title, 'Playlists'
:javascript
  window._gPlaylistsData = #{json_escape @playlists.to_json.html_safe};
.playlists-wrapper
= paginate @playlists

app/views/playlists/new.html.haml
- provide :title, 'New playlist'
= form_for @playlist, :html => { :class => 'playlist-form' } do |form|
  = form.text_field :title, :placeholder => 'Title', :autocomplete => 'off'
  = form.submit 'Create', :class => 'btn'
.playlist-tracks-wrapper
= render 'form'
.tracks-search-wrapper

app/views/playlists/show.html.haml
- provide :title, "Playlists / #{@playlist.title}"
:javascript
  window._gPlaylistData = #{json_escape @playlist.to_json.html_safe};
.playlist-tracks-wrapper
%a.spoiler-link{ :href => '#' } Add more tracks
.spoiler
  = render 'form'
  .tracks-search-wrapper

app/views/static_pages/home.html.haml
- provide :title, 'Home'
.status
  - if @playlist.nil?
    Not playing
  - else
    Now playing: #{@playlist.title}
%audio{:controls => 'controls'}
  %source{:src => 'http://localhost:8000/outer.mp3'}

app/views/static_pages/live.html.haml
- provide :title, 'Live'
- if current_user.is_broadcaster?
  .live-control
    = link_to 'Enable live', '#',:class => 'enable-live-link'
    = link_to 'Disable live', '#', :class => 'disable-live-link'
:javascript
  var flashVars = {
      appName: 'rtmp://localhost:1935/live',
      streamName:'mystream'
  };
  swfobject.embedSWF('RtmpPublisher.swf', 'rtmp-publisher', '500', '200', '9.0.0', null, flashVars);
#rtmp-publisher
  %p Flash not installed

app/views/tracks/index.html.haml
- provide :title, 'Tracks'
:javascript
  window._gTracksData = #{json_escape @tracks.to_json.html_safe};
.tracks-wrapper
= paginate @tracks

app/views/tracks/new.html.haml
- provide :title, 'Upload tracks'
.uploader
  = form_for @track, :html => { :class => "uploader-form" } do |form|
    %div
      %spam.uploader-button.btn
        Upload tracks
        = form.file_field :upload, :multiple => true, :name => "track[upload]", :class => "uploader-file-field"
  %table.uploads-table.table.table-striped.table-bordered
    %thead
      %tr
        %th Filename
        %th Progress
        %th Status
        %th Edit
    %tbody
  .upload-editor

app/views/users/index.html.haml
- provide :title, 'Users'
:javascript
  window._gUsersData = #{json_escape @users.to_json.html_safe};
.users-wrapper
= paginate @users